apiVersion: v1
kind: Service
metadata:
  name: {{ template "kplr.name" . }}
  namespace: kube-system
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "kplr.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: web
      protocol: TCP
      port: {{ .Values.service.webIntPort }}
      targetPort: web
{{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.webExtPort))) }}
      nodePort: {{ .Values.service.webExtPort }}
{{- end }}
    - name: zebra
      protocol: TCP
      port: {{ .Values.service.zebraPort }}
      targetPort: zebra
  selector:
    app: {{ template "kplr.name" . }}
    release: {{ .Release.Name }}
