apiVersion: v1
kind: Service
metadata:
  name: log-aggregator
  namespace: kube-system
spec:
  type: NodePort
  ports:
    - name: zebra
      protocol: TCP
      port: 9966
    - name: web
      protocol: TCP
      port: 8080
      nodePort: 31080
  selector:
    role: log-aggregator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    role: log-aggregator
    name: log-aggregator
    version: v1
  name: log-aggregator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      role: log-aggregator
      version: v1
  template:
    metadata:
      labels:
        role: log-aggregator
        version: v1
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: log-aggregator
          image: index.docker.io/kplr/log-aggregator:latest
          ports:
            - name: zebra
              protocol: TCP
              containerPort: 9966
            - name: web
              protocol: TCP
              containerPort: 8080
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: dockercontainers
              mountPath: /var/lib/docker/containers
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockercontainers
          hostPath:
            path: /var/lib/docker/containers
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: log-agent
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        name: log-agent
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      securityContext:
        runAsUser: 0
      containers:
        - name: log-agent
          image: index.docker.io/kplr/log-agent:latest
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: dockercontainers
              mountPath: /var/lib/docker/containers
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockercontainers
          hostPath:
            path: /var/lib/docker/containers
