apiVersion: v1
appVersion: "1.0"
name: kplr-agent
description: Logging aggregation agent
version: 0.1.0
keywords:
  - logging
  - logs
  - analytics
  - agent
home: https://github.com/kplr-io/kplr
maintainers:
  - name: Dmitry Spasibenko
    email: dspasibenko@gmail.com
